import CreationSection from '@/components/creation_section/creation_section'
import FeatureSection from 'components/feature_section/feature_section'
import Hero from 'components/hero/hero'
import Head from 'next/head'
import { Component, ReactNode } from 'react'


export default class LoopStudios extends Component{
  constructor(props: any){
    super(props)
  }

  render(): ReactNode {
      return (
        <>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <Hero />
        <FeatureSection />
        
        <CreationSection />
        </>
      )
  }
}
